import test from 'node:test';import assert from 'node:assert/strict';
import {reconcileHitlCatalog} from '../lambda/workspace/hitl-seed.mjs';
import {buildHitlCatalogItem} from '../lambda/workspace/hitl-policies.mjs';
const event={RequestType:'Create',ResourceProperties:{TableName:'SyntheticState',InitializationVersion:1}};
const at='2026-09-14T00:00:00.000Z';
test('missing catalog conditionally initializes empty configuration, never enforcement',async()=>{const calls=[];const result=await reconcileHitlCatalog(event,{async send(c){calls.push(c);return {}; }},()=>at);assert.equal(result.Data.Created,true);assert.equal(calls[1].input.ConditionExpression,'attribute_not_exists(pk) AND attribute_not_exists(sk)');assert.deepEqual(JSON.parse(calls[1].input.Item.document.S).policies,[]);});
test('existing valid nonempty catalog is retained without writes',async()=>{const catalog={schemaVersion:1,revision:2,domainId:'platform',updatedAt:at,policies:[{id:'synthetic',version:1,name:'Synthetic',enabled:false,mode:'notify_only',scope:{kind:'domain'},toolMatch:['test_*'],createdAt:at}]};let n=0;const result=await reconcileHitlCatalog(event,{async send(c){n++;assert.equal(c.constructor.name,'GetItemCommand');return {Item:buildHitlCatalogItem(catalog)};}},()=>at);assert.equal(result.Data.Created,false);assert.equal(n,1);});
test('malformed, access denied, and foreign table updates fail closed',async()=>{await assert.rejects(reconcileHitlCatalog(event,{async send(){return {Item:{bad:true}};}},()=>at));await assert.rejects(reconcileHitlCatalog(event,{async send(){throw Error('denied');}},()=>at));await assert.rejects(reconcileHitlCatalog({...event,RequestType:'Update',PhysicalResourceId:'wrong'},{},()=>at));});
test('Delete retains catalog with zero I/O',async()=>{await reconcileHitlCatalog({...event,RequestType:'Delete',PhysicalResourceId:'platform-hitl-catalog:SyntheticState:platform'},{async send(){assert.fail('write on delete');}},()=>at);});

test('concurrent initializer preserves existing valid catalog after conditional conflict',async()=>{let n=0;const item=buildHitlCatalogItem({schemaVersion:1,revision:2,domainId:'platform',updatedAt:at,policies:[]});await reconcileHitlCatalog(event,{async send(c){n++;if(n===1)return {};if(n===2)throw Object.assign(Error('conflict'),{name:'ConditionalCheckFailedException'});return {Item:item};}},()=>at);assert.equal(n,3);});

test('bounded access propagation retries retain exact conditional initialization',async()=>{let calls=0;await reconcileHitlCatalog(event,{async send(){calls++;if(calls===1)throw Object.assign(Error('propagation'),{name:'AccessDeniedException'});return {};}},()=>at,async()=>{});assert.equal(calls,3);});

test('Update retains an existing human catalog without reset or write',async()=>{let writes=0;const item=buildHitlCatalogItem({schemaVersion:1,revision:9,domainId:'platform',updatedAt:at,policies:[]});const r=await reconcileHitlCatalog({...event,RequestType:'Update',PhysicalResourceId:'platform-hitl-catalog:SyntheticState:platform',OldResourceProperties:event.ResourceProperties},{async send(c){if(c.constructor.name==='PutItemCommand')writes++;return {Item:item};}},()=>at);assert.equal(r.Data.Created,false);assert.equal(writes,0);});
test('CloudFormation actual string properties initialize safely and reject other versions',async()=>{let calls=0;const wire={RequestType:'Create',ResourceType:'Custom::PlatformHitlCatalog',ResourceProperties:{ServiceToken:'synthetic-provider',TableName:'SyntheticState',InitializationVersion:'1',ServiceTimeout:'180'}};await reconcileHitlCatalog(wire,{async send(){calls++;return {};}},()=>at);assert.equal(calls,2);for(const version of ['01','2',true,{},null,undefined,1.0000001])await assert.rejects(reconcileHitlCatalog({...wire,ResourceProperties:{...wire.ResourceProperties,InitializationVersion:version}},{async send(){assert.fail('invalid version accessed DynamoDB');}},()=>at));});
