import test from 'node:test';import assert from 'node:assert/strict';
import {createRuntimePolicyReader} from '../lambda/policy-inventory/service.mjs';
import {createPolicyInventoryHandler} from '../lambda/policy-inventory/index.mjs';
const gateway={arn:'arn:aws:bedrock-agentcore:us-west-2:111122223333:gateway/platform-tools-abcdefghij',label:'Tools'};
const engine='Example-abcdefghij',arn='arn:aws:bedrock-agentcore:us-west-2:111122223333:policy-engine/'+engine;
function reader(respond){const calls=[];return {calls,read:createRuntimePolicyReader({gateways:[gateway],client:{send:async c=>{calls.push(c);return respond(c)}}})}}
const gw=extra=>({gatewayArn:gateway.arn,gatewayId:'platform-tools-abcdefghij',status:'READY',authorizerType:'AWS_IAM',...extra});
const policy={policyId:'Limit-abcdefghij',policyArn:arn+'/policy/Limit-abcdefghij',policyEngineId:engine,name:'Limit',status:'ACTIVE',definition:{cedar:{statement:'forbid(principal, action, resource);'}}};
test('a configured Gateway without attachment is observed as not attached, never enforced',async()=>{const h=reader(()=>gw({})),r=await h.read();assert.equal(r.complete,true);assert.equal(r.gateways[0].binding,'NOT_ATTACHED');assert.equal(h.calls.length,1)});
for(const mode of ['LOG_ONLY','ENFORCE'])test(`bound ${mode} engine uses native policy records and exhausts pagination`,async()=>{let pages=0;const h=reader(c=>c.constructor.name==='GetGatewayCommand'?gw({policyEngineConfiguration:{arn,mode}}):c.constructor.name==='GetPolicyEngineCommand'?{policyEngineId:engine,policyEngineArn:arn,name:'Example',status:'ACTIVE'}:pages++===0?{policies:[policy],nextToken:'next'}:{policies:[]});const r=await h.read();assert.equal(r.complete,true);assert.equal(r.gateways[0].mode,mode);assert.equal(r.gateways[0].policies[0].statement,policy.definition.cedar.statement);assert.equal(pages,2)});
test('foreign engine bindings are never followed',async()=>{const h=reader(()=>gw({policyEngineConfiguration:{arn:arn.replace('111122223333','444455556666'),mode:'ENFORCE'}}));const r=await h.read();assert.equal(r.complete,false);assert.equal(h.calls.length,1);assert.equal(r.gateways[0].binding,'UNKNOWN')});
test('source failures preserve valid prior policy rows and distinguish unavailable from absent',async()=>{const h=reader(c=>{if(c.constructor.name==='GetGatewayCommand')return gw({policyEngineConfiguration:{arn,mode:'ENFORCE'}});if(c.constructor.name==='GetPolicyEngineCommand')return {policyEngineId:engine,policyEngineArn:arn,status:'ACTIVE'};if(!c.input.nextToken)return {policies:[policy],nextToken:'next'};throw Object.assign(new Error('private details'),{name:'ThrottlingException'})});const r=await h.read();assert.equal(r.complete,false);assert.equal(r.gateways[0].error,'THROTTLED');assert.equal(r.gateways[0].policies.length,1);assert.ok(!JSON.stringify(r).includes('private details'))});
function event(groups=['platform-admin'],headers={}){return {routeKey:'GET /api/governance/runtime-policies',rawQueryString:'',headers,requestContext:{http:{method:'GET',path:'/api/governance/runtime-policies'},authorizer:{jwt:{claims:{sub:'test-sub',token_use:'access',username:'test-user','cognito:groups':JSON.stringify(groups)}}}}}}
test('policy inventory is restricted to authenticated platform administrators',async()=>{let calls=0;const handle=createPolicyInventoryHandler({read:async()=>{calls++;return {ok:true}}});assert.equal((await handle(event())).statusCode,200);assert.equal((await handle(event(['domain-lead','domain-operations']))).statusCode,403);assert.equal(calls,1)});
test('demo role switching cannot elevate a non-admin or retain admin access in Builder context',async()=>{const handle=createPolicyInventoryHandler({read:async()=>({ok:true}),verify:async()=>true});assert.equal((await handle(event(['domain-lead','demo-operator'],{'x-demo-role':'admin'}))).statusCode,403);assert.equal((await handle(event(['platform-admin','demo-operator'],{'x-demo-role':'builder','x-active-domain':'operations'}))).statusCode,403)});
test('query-selected gateways, bodies and mutation routes are rejected before reads',async()=>{const handle=createPolicyInventoryHandler({read:async()=>{throw Error('must not read')}});assert.equal((await handle({...event(),rawQueryString:'gateway=foreign'})).statusCode,400);assert.equal((await handle({...event(),body:'{}'})).statusCode,400);assert.equal((await handle({...event(),routeKey:'POST /api/governance/runtime-policies'})).statusCode,404)});

test('ID tokens and missing subjects never reach policy reads',async()=>{let calls=0;const handle=createPolicyInventoryHandler({read:async()=>{calls++;return {ok:true}}});const id=event();id.requestContext.authorizer.jwt.claims.token_use='id';assert.equal((await handle(id)).statusCode,401);const noSubject=event();delete noSubject.requestContext.authorizer.jwt.claims.sub;assert.equal((await handle(noSubject)).statusCode,401);assert.equal(calls,0)});
