import test from 'node:test';import assert from 'node:assert/strict';
import {createRecordDisplayCache} from '../lambda/control-plane/record-cache.mjs';
const summary={registryId:'registry1',recordId:'record1',recordArn:'arn:registry1/record/record1',name:'draft',type:'MCP',status:'PENDING_APPROVAL',updatedAt:new Date('2026-09-17T00:00:00Z')};
const record=()=>({...summary,descriptor:{value:'validated'}});
test('unchanged fresh list versions reuse validated details, without sharing mutable objects',async()=>{let calls=0;const read=createRecordDisplayCache(),load=async()=>{calls++;return record()};const first=await read(summary,load);first.descriptor.value='mutated';const second=await read(summary,load);assert.equal(calls,1);assert.equal(second.descriptor.value,'validated');second.descriptor.value='also mutated';assert.equal((await read(summary,load)).descriptor.value,'validated')});
test('status, version timestamp and Registry scope changes must fetch details again',async()=>{let calls=0;const read=createRecordDisplayCache();for(const s of [summary,{...summary,status:'APPROVED'},{...summary,updatedAt:new Date('2026-09-17T00:01:00Z')},{...summary,registryId:'other',recordArn:'arn:other/record/record1'}])await read(s,async()=>{calls++;return {...record(),...s}});assert.equal(calls,4)});
test('freshness expires from completion and hits do not extend it',async()=>{let clock=0,calls=0;const read=createRecordDisplayCache({now:()=>clock,ttlMs:10});const load=async()=>{calls++;return record()};await read(summary,load);clock=9;await read(summary,load);clock=11;await read(summary,load);assert.equal(calls,2)});
test('failures, missing versions, projection faults and raced versions are never cached',async()=>{const read=createRecordDisplayCache();let calls=0;const failure=async()=>{calls++;throw Error('throttled')};await assert.rejects(read(summary,failure));await assert.rejects(read(summary,failure));assert.equal(calls,2);for(const [s,value] of [[{...summary,updatedAt:undefined},record()],[summary,null],[summary,{...record(),updatedAt:new Date('2026-09-17T01:00:00Z')}]]){calls=0;const load=async()=>{calls++;return value};await read(s,load);await read(s,load);assert.equal(calls,2)}});
test('the cache stays bounded',async()=>{let calls=0;const read=createRecordDisplayCache({maxEntries:1});const load=async()=>{calls++;return record()};await read(summary,load);await read({...summary,recordId:'record2'},load);await read(summary,load);assert.equal(calls,3)});
